// <auto-generated />
namespace Blog.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostTitleNonNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostTitleNonNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201702091943400_PostTitleNonNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
